
name: Portfolio 

on:
  push:
    branches:
      - main
     workflow-dispatch:
     
permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
      
    steps:

       # get the access to the repository via pre-built action
      - name: checkout code
        uses: actions/checkout@v4
      
      - name: setup github pages
        uses: actions/configure-pages@v4
    
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        
        with:
          path: ./dist  # or your actual build output directory, e.g., ./out, .next, etc.   
      
      - name: deploy to github pages
        uses: actions/deploy-pages@v4
      
      

  
